# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20170622_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
