# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_body', models.CharField(max_length=30, verbose_name='Номер или email')),
            ],
            options={
                'verbose_name': 'Содержания',
                'verbose_name_plural': 'Содержании',
            },
        ),
        migrations.CreateModel(
            name='TitleFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_body', models.CharField(max_length=30, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.AddField(
            model_name='listfooter',
            name='title_footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footer_data.TitleFooter'),
        ),
    ]
