# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 19:44
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_body', models.CharField(max_length=30, verbose_name='Тема')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Обзор')),
            ],
        ),
        migrations.AlterField(
            model_name='listfooter',
            name='list_body',
            field=models.CharField(max_length=30, verbose_name='Содержания'),
        ),
        migrations.AlterField(
            model_name='titlefooter',
            name='title_body',
            field=models.CharField(max_length=50, verbose_name='Тема'),
        ),
    ]
