# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer_data', '0002_auto_20170623_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставка'},
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='list_body',
            new_name='title',
        ),
    ]
