# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer_data', '0004_auto_20170626_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfooter',
            name='list_body',
            field=models.CharField(max_length=40, verbose_name='Содержания'),
        ),
    ]
