# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='Бишкек', max_length=100, verbose_name='Город'),
        ),
    ]
